### ISSUE TITLE
Update Genre Delete Funktion

### ISSUE THREAD

**Issue by Kieberts** [ELITE-Kinoticketsystem/Backend-KTS#105]
## Problem 
Deleting a Genre might not always work, because it references to the movieGenre Table. 

## Solution Idea
When deleting a genre, also delete entries in movieGenre Table containing the genre, which is to be deleted. 

Frontend or backend should implement a warning message for user to conform, delete all the references.

**Comment by Hajny25** [comment]
@EliasSC30

**Comment by Kieberts** [comment]
Done
